### ISSUE TITLE
[Question] Help needed on using multiple grep tags

### ISSUE THREAD

**Issue by RaghavendraVasa** [marksandspencer/nx-plugins#104] opened 2023-06-25 09:17 UTC
I am trying to run my playwright tests using grep tags. I have two tags @tag1 and @tag2.
@tag1 is having 10 tests and @tag2 is having 5 tests. I want to run both the tags.
If I give one tag it is working fine, the problem is with multiple tags. 
Can anyone give an example for running this

**Comment by andreacaldera** [comment] 2023-06-26 08:35
Hey @RaghavendraVasa 

You should be able to use playwright tags as described here https://playwright.dev/docs/test-annotations#tag-tests

Hope this helps

**Comment by andreacaldera** [comment] 2023-06-26 08:36
Closing as this question relates to playwright itself and not this plugin

**Closed by andreacaldera** 2023-06-26 08:36 UTC

**Comment by RaghavendraVasa** [comment] 2023-06-27 03:48
I have followed the documentation and tried using the same.
Command used : nx e2e web-client-e2e --skip-nx-cache --grep="@UserAuth|@ListView"
I am getting the below error
![image](https://github.com/marksandspencer/nx-plugins/assets/118344579/b53e8466-80f1-4059-a550-24adeaed736e)

**Comment by andreacaldera** [comment] 2023-06-27 09:14
It looks like the issue is related with the pipe symbol, can you please try 
`nx e2e web-client-e2e --skip-nx-cache --grep="@userauth\|@listview"`

**Comment by RaghavendraVasa** [comment] 2023-06-27 09:28
@andreacaldera 
Tried running with: `nx e2e web-client-e2e --skip-nx-cache --grep="@UserAuth\|@ListView"`
It is giving me the same error
![image](https://github.com/marksandspencer/nx-plugins/assets/118344579/4de8a92a-1e11-463b-839a-c497fbf61b0d)

**Comment by mcalthrop** [comment] 2023-06-27 10:05
@RaghavendraVasa Try with single quotes:

```sh
nx e2e web-client-e2e --skip-nx-cache --grep='@UserAuth|@ListView'
```

**Comment by RaghavendraVasa** [comment] 2023-06-27 10:21
@mcalthrop 
Same result with single quotes as well
command used: `nx e2e web-client-e2e --skip-nx-cache --grep='@UserAuth|@ListView'`
![image](https://github.com/marksandspencer/nx-plugins/assets/118344579/fa362db2-0ff2-40a7-acdf-bc340ed5dd3e)

**Comment by andreacaldera** [comment] 2023-06-27 11:47
I tried this on my own project and it works with single and double quotes but I had to escape the pipe symbol.
This may be related to your OS? What are you running on?

Are you able to reproduce this problem on an open source project?
I'd suggest creating a new NX workspace with some e2e tests and try it there. If could push that to a public repo we would also be able to try and advise.
