### ISSUE TITLE
Error while running `nx generate @mands/nx-playwright:project` command

### ISSUE THREAD

**Issue by dipushrestha** [marksandspencer/nx-plugins#89] opened 2023-03-29 12:46 UTC
## Describe the bug
Error while running `nx generate @mands/nx-playwright:project` command.

## To reproduce
Run the command `yarn nx generate @mands/nx-playwright:project <app>-e2e --project <app>`

## Expected behaviour
Generation of playwright project in the apps directory.

## Screenshots
![image](https://user-images.githubusercontent.com/36785868/228538604-13c60a09-99d7-48f9-9f72-6f300401bd87.png)

**Comment by andreacaldera** [comment] 2023-03-29 14:29
Hi @dipushrestha ,

Could you please provide more details (e.g. version of node, yarn, etc) and an sample project where we can reproduce this issue?

I've quickly tried [here](https://github.com/andreacaldera/test-nx-playwright-e2e/pull/1) and it seems fine with the latest version

**Comment by dipushrestha** [comment] 2023-03-29 14:36
Here is the `nx report`
```
>  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : linux x64
   yarn : 1.22.17
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.6.3
   @nrwl/workspace         : 15.6.3
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.8.5
   @nrwl/detox             : 15.7.2
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.6.3
   @nrwl/js                : 15.8.6
   @nrwl/next              : 15.8.6
   @nrwl/react             : 15.8.6
   @nrwl/react-native      : 15.8.6
   @nrwl/tao               : 15.7.2
   @nrwl/vite              : 15.8.6
   @nrwl/webpack           : 15.8.6
   typescript              : 4.9.5
   ---------------------------------------
   Community plugins:
   @mands/nx-playwright  : 0.2.4
   @nx-extend/e2e-runner : 2.3.1
   @nx-extend/playwright : 1.2.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/jest@15.8.6
     - @nrwl/linter@15.6.3
     - @nrwl/workspace@15.6.3
     - @nrwl/cypress@15.8.5
     - @nrwl/devkit@15.8.6
     - @nrwl/eslint-plugin-nx@15.6.3
     - @nrwl/js@15.8.6
     - @nrwl/next@15.8.6
     - @nrwl/react@15.8.6
     - @nrwl/react-native@15.8.6
     - @nrwl/vite@15.8.6
     - @nrwl/webpack@15.8.6
```

**Comment by andreacaldera** [comment] 2023-03-29 14:39
Did you follow the steps on the sample PR I shared? Can you provide a project where this issue can be reproduced please?

**Comment by dipushrestha** [comment] 2023-03-29 14:44
The link is not accessible. The repo is private so I can't share the project.

**Comment by andreacaldera** [comment] 2023-03-29 14:51
Please check again

**Comment by rockse** [comment] 2023-06-14 08:17
Hey @dipushrestha, we will close this issue because we haven't gotten a response yet. Happy to reopen it once you have shared more details with us.

**Closed by rockse** 2023-06-14 08:17 UTC
